name: Container Image
on:
  push:
    tags:        
      - '**'

jobs:
  build:
    name: Build container image and push it to registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: clbbot
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Login to GitHub Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Amazon ECR Public # https://github.com/aws-actions/amazon-ecr-login/issues/116
        uses: docker/login-action@v2
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        env:
          AWS_REGION: us-east-1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            KANIKO_VERSION=1.13.0
            ENV_CRED_HELPER_VERSION=1.2.2
            ECR_CRED_HELRER_VERSION=0.7.1
            GCR_CRED_HELRER_VERSION=2.1.10
            MANIFEST_TOOL_VERSION=2.0.8
            SKOPEO_VERSION=1.9.3
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            cookielab/container-image-tools:${{ github.ref_name }}
            public.ecr.aws/cookielab/container-image-tools:${{ github.ref_name }}
            ghcr.io/${{ github.repository_owner }}/container-image-tools:${{ github.ref_name }}

      - name: Build and push - AWS
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.aws
          build-args: |
            VERSION=${{ github.ref_name }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            cookielab/container-image-tools:${{ github.ref_name }}-aws
            public.ecr.aws/cookielab/container-image-tools:${{ github.ref_name }}-aws
            ghcr.io/${{ github.repository_owner }}/container-image-tools:${{ github.ref_name }}-aws
